### ISSUE TITLE
vikeVuePinia causes error

### ISSUE THREAD

**Issue by u007** [vikejs/vike-vue#139]
```+config.ts
import vikeVue from "vike-vue/config";
import type { Config } from "vike/types";
import Head from "../layouts/HeadDefault.vue";
import Layout from "../layouts/LayoutDefault.vue";
import vikeVuePinia from 'vike-vue-pinia/config'
// Default config (can be overridden by pages)
export default {
  Layout,
  Head,
  // <title>
  title: "BackOffice",
  extends: [vikeVue, vikeVuePinia],
} satisfies Config;
```

error:
```
4:45:05 PM [vike][request(1)] Following error was thrown by the onRenderHtml() hook defined at vike-vue/renderer/onRenderHtml
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '_context' -> object with constructor 'Object'
    --- property 'app' closes the circle
    at JSON.stringify (<anonymous>)
    at Object.toDisplayString (/Users/james/www/admin/node_modules/.pnpm/@vue+shared@3.4.29/node_modules/@vue/shared/dist/shared.cjs.js:465:154)
    at Module.ssrInterpolate (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:180:35)
    at _sfc_ssrRender (/Users/james/www/admin/pages/index/+Page.vue:1:1)
    at renderComponentSubTree (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:693:9)
    at renderComponentVNode (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:637:12)
    at renderVNode (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:753:14)
    at renderVNodeChildren (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:769:5)
    at ssrRenderSlotInner (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:118:7)
    at Module.ssrRenderSlot (/Users/james/www/admin/node_modules/.pnpm/@vue+server-renderer@3.4.29_vue@3.4.29/node_modules/@vue/server-renderer/dist/server-renderer.cjs.js:93:3)
4:45:05 PM [vike][request(1)] HTTP response / 500
4:45:05 PM [vike@0.4.177][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
```

**Comment by brillout** [comment]
Can you publishing a reproduction?

**Comment by u007** [comment]
hi sorry realised it was my code issue on my store due to cody.
im encountering new error with vike ts config

https://github.com/u007/vike-admin

```
1:10:19 AM [vike@0.4.177][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at isVirtualFileId (file:///Users/james/www/admin/node_modules/.pnpm/vike@0.4.177_vite@5.3.1/node_modules/vike/dist/esm/utils/virtual-files.js:13:5)
    at ResolveIdContext.resolveId (file:///Users/james/www/admin/node_modules/.pnpm/vike@0.4.177_vite@5.3.1/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/index.js:33:17)
    at PluginContainer.resolveId (file:///Users/james/www/admin/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49463:17)
    at ResolveIdContext.resolve (file:///Users/james/www/admin/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49623:15)
    at ResolveIdContext.handler (file:///Users/james/www/admin/node_modules/.pnpm/vike@0.4.177_vite@5.3.1/node_modules/vike/dist/esm/node/plugin/plugins/fileEnv.js:35:34)
    at PluginContainer.resolveId (file:///Users/james/www/admin/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49462:22)
    at ResolveIdContext.resolve (file:///Users/james/www/admin/node_modules/.pnpm/vite@5.3.1/node_modules/vite/dist/node/chunks/dep-BcXSligG.js:49623:15)
    at viteResolve (file:///Users/james/www/admin/node_modules/.pnpm/vite-tsconfig-paths@4.3.2_typescript@5.5.2_vite@5.3.1/node_modules/vite-tsconfig-paths/src/index.ts:162:12)
```

**Comment by u007** [comment]
hi nvm, ive fixed it using manual resolve,
but ive a another question about adding module like ant design vue, how do i access app.use(xxx)

**Comment by phonzammi** [comment]
> how do i access app.use(xxx)

ever use [onCreateApp](https://github.com/vikejs/vike-vue/blob/main/examples/full/pages/%2BonCreateApp.ts) hook ?
